[workspace]
resolver = "2"
members = [ "crates/bindings",
    "crates/cli"
, "crates/metaboard"]

[workspace.dependencies]
reqwest = { version = "0.11.17", features = ["json"] }
tokio = { version = "1.28.0", features = ["full"] }
cynic-codegen = { version = "3.4.0", features = ["rkyv"] }
cynic = "3.4.0"
thiserror = "1.0.56"
insta = { version = "1.34.0" }
alloy-primitives = "0.5.0"
alloy-sol-types = { version = "0.6.3", features = ["json"] }
serde_json = "1.0.108"

