[profile.default]

solc = "0.8.25"

# optimizer settings for snapshotting.
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 5096

[etherscan]
bera = { key = "${ETHERSCAN_API_KEY}", chain = 80094, url = "https://api.berascan.com/api" }
sonic = { key = "${ETHERSCAN_API_KEY}", chain = 146, url = "https://api.sonicscan.org/api" }
