[profile.default]

solc = "0.8.25"
auto_detect_solc = false

# optimizer settings for snapshotting.
optimizer = true
optimizer_runs = 1000000
evm_version = "cancun"

bytecode_hash = "none"
cbor_metadata = false
ffi = true

libs = ["dependencies"]

fs_permissions = [
  { access = "read", path = "subgraph/networks.json" },
  { access = "read", path = "subgraph/subgraph.yaml" },
]

[fuzz]
runs = 5096

[dependencies]
forge-std = "1.16.1"
"rain-deploy" = "0.1.2"

[soldeer]
recursive_deps = false

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
flare = "${FLARE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
arbitrum = { key = "${CI_DEPLOY_ARBITRUM_ETHERSCAN_API_KEY}" }
base = { key = "${CI_DEPLOY_BASE_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${CI_DEPLOY_BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
flare = { key = "${CI_DEPLOY_FLARE_ETHERSCAN_API_KEY}" }
polygon = { key = "${CI_DEPLOY_POLYGON_ETHERSCAN_API_KEY}" }
