[package]
name = "rain-metadata-bindings"
version = "0.1.0"
edition = "2021"
description = "Solidity bindings for rain metadata."
license.workspace = true
author.workspace = true
repository = "https://github.com/rainlanguage/rain.metadata"

[dependencies]
alloy = { workspace = true }
