on: [push]

name: test cli

jobs:
  check:
    name: Cli test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Run cargo test
        run: cd cli && cargo test