name: Manual rs release
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: |
          git config --global user.email "noreply@rainlang.xyz"
          git config --global user.name "Rain CI"
      - run: nix develop --command cargo release --no-confirm --execute alpha
