name: MetaBoard Subgraph CI
on: [push]
env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./subgraph

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix run .#rainix-sol-prelude
      - run: nix run .#rainix-rs-prelude

      - name: install npm dependencies
        run: nix develop --command init

      - name: Build Docker Compose images
        run: |
          nix develop --command docker-down
          nix develop --command docker-up


      - name: Run Subgraph tests
        run: nix develop --command ci-test

      - name: Stop containers
        run: nix develop --command docker-down
