name: MetaBoard Subgraph CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Start docker container
        run: docker-compose -f subgraph/docker/docker-compose.yml up -d

      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check


      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run test
        run: cargo run --manifest-path metaboard-cli/Cargo.toml test

      - name: Stop docker container
        run: docker-compose -f subgraph/docker/docker-compose.yml down

