name: MetaBoard Subgraph CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Pull Docker image
        run: docker pull rainprotocol/matchstick:main

      - name: Install Nix inside Docker
        run: |
          docker run rainprotocol/matchstick:main curl -L https://nixos.org/nix/install | sh -s -- --daemon

      - name: Run tests inside Docker
        run: docker run rainprotocol/matchstick:main nix develop --command subgraph-test