name: MetaBoard Subgraph CI
on: [push]
env:
  DEPLOYER_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable


      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run test
        run: cargo run --manifest-path metaboard-cli/Cargo.toml test
