name: MetaBoard Subgraph CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Node modules
        working-directory: ./subgraph
        run: |
          docker compose run matchstick sh -c "cd /matchstick && npm install && npm install -g @graphprotocol/graph-cli && graph codegen && graph build"

      - name: Run Docker container
        run: |
          docker compose -f ./subgraph/docker-compose.yml up --abort-on-container-exit
