name: MetaBoard Subgraph CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build matchstick
        working-directory: ./subgraph
        run: |
          docker compose run matchstick sh -c "cd /matchstick && npm install && graph codegen && graph build"

      - name: Run Docker container
        working-directory: ./subgraph
        run: |
          docker compose up --abort-on-container-exit
