name: MetaBoard Subgraph CI
on: [push]

jobs:
  subgraph-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Start docker container
        run: docker-compose -f subgraph/docker/docker-compose.yml up -d

      - name: install npm dependencies
        working-directory: ./subgraph
        run: nix-shell --run init

      - name: Run test
        run: cargo run --manifest-path metaboard-cli/Cargo.toml test

      - name: Stop docker container
        run: docker-compose -f subgraph/docker/docker-compose.yml down
