name: MetaBoard Subgraph CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build Docker image
        run: docker build -t matchstick ./subgraph

      - name: Run Docker container
        run: |
             docker run -it --rm --mount type=bind,source=./,target=/matchstick matchstick
